git:
  depth: 3
  quiet: true
language: node_js
dist: trusty
sudo: required
node_js:
 # Use the explicit NodeJS LTS version 8.9.4 to avoid any automatic upgrade of the version.
  - '8.9.4'

install:
    - echo "no install"
    - export HEAD_SHA_BRANCH="$(git merge-base origin/$TRAVIS_BRANCH HEAD)"
    - echo "Stampo1:" $HEAD_SHA_BRANCH

branches:
  only:
  - master
  - development
  - /.*old-env.*/
  - /.*next-release.*/
  - /.*beta.*/
  - /.*greenkeeper.*/

script:
    - export HEAD_SHA_BRANCH="core"
    - echo "Stampo1:" $HEAD_SHA_BRANCH


# TRAVIS_PULL_REQUEST == false means is running on dev branch and is not a PR
stages:
  - name: Warm Up Cache & Lint & Build Dist
  - name: Unit test
  - name: e2e Test
  - name: Deploy PR

addons:
    chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3 # give xvfb some time to start

jobs:
    include:
        - stage: Warm Up Cache & Lint & Build Dist
          name:  Warm Up Cache & Lint & Build Dist
          script:
            - echo "Stampo2:" $HEAD_SHA_BRANCH
            - echo 'Warm'
        - stage: Unit test
          if: HEAD_SHA_BRANCH ='core'
          name: core
          script:  echo 'core'
        - stage: Unit test
          name: content
          script:  echo 'content'
        - stage: Unit test
          if: HEAD_SHA_BRANCH ='core'
          name: process
          script: echo 'process'

# Send coverage data to codecov
after_success:
    bash <(curl -s https://codecov.io/bash) -X gcov

cache:
  directories:
  - node_modules
  - demo-shell/dist
  - tmp
