language: node_js
dist: trusty
sudo: false
node_js:
  - '8.9.4'

install:
  echo "no install"

branches:
  only:
  - master
  - development

stages:
  - name: Warm Up Cache
    if: branch = master
  - name: Warm Up Cache & Lint & Build Dist
    if: branch != master

addons:
    chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

before_install:
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

jobs:
    include:
        - stage: Warm Up Cache
          script:
          - npm install
        - stage: Warm Up Cache & Lint & Build Dist
          script:
          - npm install

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "YOUR GIT USER NAME"
  - git config --local user.email "YOUR GIT USER EMAIL"
  - export TRAVIS_TAG=$(grep -m1 version package.json | awk '{ print $2 }' | sed 's/[", ]//g')
  - echo "Create tag:" ${TRAVIS_TAG}
  - git tag ${TRAVIS_TAG}
  - export RELEASE_FILE_NAME=${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}
  - echo "Create zip:" ${RELEASE_FILE_NAME}
  - tar -zcf ${RELEASE_FILE_NAME}.tar.gz ${REPO}

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: ${RELEASE_FILE_NAME}.tar.gz
  skip_cleanup: true

# Send coverage data to codecov
after_success:
  bash <(curl -s https://codecov.io/bash) -X gcov

cache:
  directories:
  - node_modules
  - dist
