language: node_js
dist: trusty
sudo: required
node_js:
 # Use the explicit NodeJS LTS version 8.9.4 to avoid any automatic upgrade of the version.
  - '8.9.4'

cache:
  directories:
  - node_modules
  - demo-shell/dist
  - tmp

branches:
  only:
  - master
  - development

jobs:
    include:
        - stage: Warm Up
          name:  Warm Up
          env: AFFECTED='core'
          script:
             echo 'warm'
        - stage: Unit test
          if: AFFECTED ='core'
          name: core
          script:  echo 'core'
        - stage: Unit test
          if: AFFECTED ='process'
          name: process
          script:  echo 'core'

addons:
    chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3 # give xvfb some time to start
# jobs:
#   include:
#     - stage: Publish alpha to NPM
#       before_install: skip
#       install: skip
#       script: skip
#       deploy:
#         provider: script
#         script: (./scripts/update-version.sh -v $(./scripts/next_version.sh)-$(git rev-parse HEAD) -vj $(npm view alfresco-js-api@alpha version) -gnu) && (./scripts/npm-publish.sh -r $NPM_REGISTRY_ADDRESS -token $NPM_REGISTRY_TOKEN -t alpha --sleep 20 || exit 1;);
#         on:
#           branch: development
#         skip_cleanup: true
#     - stage: Publish beta to NPM
#       before_install: skip
#       install: skip
#       script: skip
#       deploy:
#         provider: script
#         script: (./scripts/update-version.sh -v $TRAVIS_TAG -gnu) && (./scripts/npm-publish.sh -r $NPM_REGISTRY_ADDRESS -token $NPM_REGISTRY_TOKEN -t beta --sleep 20 || exit 1;);
#         on:
#           tags: true
#         skip_cleanup: true


# Send coverage data to codecov
after_success:
    bash <(curl -s https://codecov.io/bash) -X gcov
