language: node_js
dist: trusty
sudo: false
node_js:
  - '8.9.4'

install:
  echo "no install"

branches:
  only:
  - master
  - development

stages:
  - name: Warm Up Cache
    if: branch = master
  - name: Warm Up Cache & Lint & Build Dist
    if: branch != master

addons:
    chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

before_install:
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

jobs:
    include:
        - stage: Warm Up Cache
          script:
          - npm install
        - stage: Warm Up Cache & Lint & Build Dist
          script:
          - npm install

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "YOUR GIT USER NAME"
  - git config --local user.email "YOUR GIT USER EMAIL"
  - export TRAVIS_TAG=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
  - echo "Create tag:" $TRAVIS_TAG
  - git tag $TRAVIS_TAG
  - export BODY=$(cat ./docs/release-notes/RelNote250.md)

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  body: "# Alfresco Application Development Framework, version 2.5.0 Release Note\n\nThese release notes provide information about the **2.5.0 release**\nof the Alfresco Application Development Framework.\nThis is the latest **General Available**\nrelease of the Application Development Framework, which contains the Angular components to build a Web Application on top of the Alfresco Platform.\nThe release can be found on GitHub at\n[this location.](https://github.com/Alfresco/alfresco-ng2-components/releases/tag/1.7.0)"
  skip_cleanup: true

# Send coverage data to codecov
after_success:
  bash <(curl -s https://codecov.io/bash) -X gcov

cache:
  directories:
  - node_modules
  - dist
